#!/usr/bin/env ruby
# frozen_string_literal: true

require 'nmax'

module NmaxRunner
  HELP_MESSAGE = 'Usage: cat sample_data.txt | nmax [number_of_largest_integers_to_count]'

  def self.run
    nmax = Nmax.build(parse_cli)
    nmax.sorted_result { |s| puts s }
  end

  def self.parse_cli
    if !File.pipe?($stdin) || ARGV.empty? || ARGV.size > 1 || !ARGV[0].match(/\A-?\d+\z/)
      puts HELP_MESSAGE
      exit(0)
    end

    {
      numbers_limit: ARGV[0].to_i,
      stream: $stdin
    }
  end
end

NmaxRunner.run
